class PhtClient

  @client: HttpClient

  @refresh_client: HttpClient

  @content_uri: URI::Generic

  @refresh_uri: URI::Generic

  @tokens: Tokens

  def initialize: (URI::Generic, URI::Generic, Tokens) -> void

  def fetch_content_post: (int) -> Hash[string, untyped]

  def fetch_last_top_level_comment_id: (int) -> (int | nil)

  def load_fix_page: -> Hash[int, Hash[string, untyped]]

  def load_page: -> Hash[string, untyped]

  def load_pages: -> Hash[int, Hash[string, untyped]]

  def load_wiki_ids: -> ::Array[int]

  def refresh_tokens: () -> void

  private

  def call_with_retry: (URI::Generic, int, Symbol) -> Hash[string, untyped]

end
