class PostsChecker

  @adapter: PhtPostAdapter

  @check_post_strategy: CheckPostStrategy

  def initialize: (CheckPostStrategy, PhtPostAdapter) -> void

  def check_posts: (::Array[TablePost]) -> ::Array[Hash[Symbol, untyped]]

end
