class ContentPostAdapter
  CELL_IDX: Hash[Symbol, int]

  @content_uri: URI::Generic

  def get_post_id: (TablePostEntry) -> int

  def get_time_table: (::Array[Object]) -> ::Array[Object]

  def header?: (::Array[Object]) -> bool

  def initialize: (URI::Generic) -> void

  def multi_table?: -> bool

  def post?: (::Array[Object]) -> bool

  def to_table_post_entry: (::Array[Object]) -> TablePostEntry
end
