class ContentGetPostsInfoStrategy

  CELL_IDX: Hash[Symbol, int]

  @sheets_client: SheetsClient

  @spreadsheet_id: string

  @table: string

  def initialize: (SheetsClient, string, string) -> void

  def fetch_posts_info: -> [::Array[TablePost], string]

end
