class ContentCheckPostStrategy

  @adapter: PhtPostAdapter

  @pht_client: PhtClient

  @post_service: PhtPostService

  def initialize: (PhtClient, PhtPostService) -> void

  def check_post: (TablePost, Hash[int, untyped]) -> Hash[Symbol, untyped]

end
