class ContentGetPostsInfoStrategy

  @sheets_client: SheetsClient

  @spreadsheet_id: string

  @table: string

  @adapter: PhtPostAdapter

  def initialize: (SheetsClient, string, string, PhtPostAdapter) -> void

  def fetch_posts_info: -> [::Array[TablePost], string]

end
