class ContentGetPostsInfoStrategy

  @sheets_client: SheetsClient

  @spreadsheet_id: string

  @table: string

  @adapter: PhtPostAdapter

  def initialize: (SheetsClient, string, string, PhtPostAdapter) -> void

  def fetch_posts_info: -> Hash[string, [::Array[TablePost], string]]

  def parse_subtable: (::Array[::Array[Object]])-> [::Array[TablePost], string]

end
